AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyALB
      Scheme: internet-facing
      Type: application
      Subnets:
        - subnet-0aceebfe8d46837e7 
        - subnet-0b14d636b6d244a5e 
      SecurityGroups:
        - sg-01fa27a8d234abe66      
      Tags:
        - Key: Name
          Value: MyALB
  MyALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MyALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: MyTargetGroup
      Port: 80
      Protocol: HTTP
      VpcId: vpc-03428c3a20abec02b
