AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: myinstance1
      AllocatedStorage: 10
      DBInstanceClass: db.t2.micro
      Engine: mysql
      EngineVersion: '5.7'
      MasterUsername: admin
      MasterUserPassword: admin1234
      PubliclyAccessible: True
      VPCSecurityGroups:
       - sg-0c51f4451637cefac  
      AvailabilityZone: us-east-1a 
      BackupRetentionPeriod: 7  
      MultiAZ: false  
      StorageType: gp2  